"""empty message

Revision ID: 0bcbf6232e17
Revises: b0a29b04c1a3
Create Date: 2022-06-20 09:24:22.593484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bcbf6232e17'
down_revision = 'b0a29b04c1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bird', sa.Column('user_id', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bird', 'user_id')
    # ### end Alembic commands ###
