"""empty message

Revision ID: 1df39ac023c8
Revises: b7572d97ac5f
Create Date: 2022-06-23 20:21:13.531164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df39ac023c8'
down_revision = 'b7572d97ac5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evil_cat_fact',
    sa.Column('refresh', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('refresh')
    )
    op.alter_column('bird', 'county',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('bird', 'date_month',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('bird', 'date_day',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bird', 'date_day',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('bird', 'date_month',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('bird', 'county',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_table('evil_cat_fact')
    # ### end Alembic commands ###
