"""empty message

Revision ID: 4ba32fce9c2a
Revises: ae2e08855ab5
Create Date: 2022-06-10 19:04:06.438627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba32fce9c2a'
down_revision = 'ae2e08855ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bird', sa.Column('bird_id', sa.String(length=40), nullable=False))
    op.drop_column('bird', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bird', sa.Column('id', sa.VARCHAR(length=40), server_default=sa.text("nextval('bird_id_seq'::regclass)"), autoincrement=False, nullable=False))
    op.drop_column('bird', 'bird_id')
    # ### end Alembic commands ###
