"""empty message

Revision ID: 5f98e4b87b1a
Revises: 4de0432a4420
Create Date: 2022-07-21 13:13:46.375941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f98e4b87b1a'
down_revision = '4de0432a4420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('user', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('fav_bird', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fav_bird')
    op.drop_column('user', 'bio')
    op.drop_table('followers')
    # ### end Alembic commands ###
