"""empty message

Revision ID: 6e3234cf1515
Revises: 5f98e4b87b1a
Create Date: 2022-08-09 17:46:29.038136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3234cf1515'
down_revision = '5f98e4b87b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('react',
    sa.Column('common_name', sa.String(length=100), nullable=False),
    sa.Column('latin_name', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('habitat', sa.String(length=75), nullable=True),
    sa.Column('diet', sa.String(length=75), nullable=True),
    sa.Column('pledge', sa.Integer(), nullable=True),
    sa.Column('fun_fact', sa.String(length=150), nullable=True),
    sa.Column('conservation', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=75), nullable=True),
    sa.PrimaryKeyConstraint('common_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('react')
    # ### end Alembic commands ###
