"""empty message

Revision ID: a49544a7d294
Revises: 
Create Date: 2022-05-29 10:44:02.431174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49544a7d294'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bird',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latin_name', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('habitat', sa.String(length=75), nullable=True),
    sa.Column('food', sa.String(length=75), nullable=True),
    sa.Column('behaviors', sa.String(length=100), nullable=True),
    sa.Column('weight_g', sa.Integer(), nullable=True),
    sa.Column('conservation', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bird')
    # ### end Alembic commands ###
