"""empty message

Revision ID: b7572d97ac5f
Revises: d4a6969f70a8
Create Date: 2022-06-21 10:21:50.940818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7572d97ac5f'
down_revision = 'd4a6969f70a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bird', sa.Column('date_year', sa.String(length=5), nullable=False))
    op.add_column('bird', sa.Column('date_month', sa.String(length=5), nullable=False))
    op.add_column('bird', sa.Column('date_day', sa.String(length=5), nullable=False))
    op.alter_column('bird', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bird', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('bird', 'date_day')
    op.drop_column('bird', 'date_month')
    op.drop_column('bird', 'date_year')
    # ### end Alembic commands ###
