"""empty message

Revision ID: d4a6969f70a8
Revises: e9c932f2bafa
Create Date: 2022-06-21 08:15:22.573960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a6969f70a8'
down_revision = 'e9c932f2bafa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_bird_search',
    sa.Column('country', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('county', sa.String(length=40), nullable=True),
    sa.Column('obsDate', sa.String(length=40), nullable=True),
    sa.Column('days', sa.String(length=40), nullable=True),
    sa.Column('hotspots', sa.String(length=40), nullable=True),
    sa.Column('interesting', sa.String(length=40), nullable=True),
    sa.Column('comName', sa.String(length=40), nullable=True),
    sa.Column('checklist', sa.String(length=40), nullable=True),
    sa.Column('locName', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('country')
    )
    op.drop_constraint('bird_common_name_key', 'bird', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bird_common_name_key', 'bird', ['common_name'])
    op.drop_table('e_bird_search')
    # ### end Alembic commands ###
