"""empty message

Revision ID: e9c932f2bafa
Revises: 0bcbf6232e17
Create Date: 2022-06-20 15:36:18.834726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c932f2bafa'
down_revision = '0bcbf6232e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bird', sa.Column('outing', sa.String(length=100), nullable=True))
    op.add_column('bird', sa.Column('backyard', sa.String(length=10), nullable=True))
    op.add_column('bird', sa.Column('annual', sa.String(length=10), nullable=True))
    op.add_column('bird', sa.Column('lifetime', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bird', 'lifetime')
    op.drop_column('bird', 'annual')
    op.drop_column('bird', 'backyard')
    op.drop_column('bird', 'outing')
    # ### end Alembic commands ###
